{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.peerCert.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.certManager.peerCert" .  }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.certManager.peerCert" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "etcd.certManager.peerCert" .  }}
  secretTemplate:
    labels:
      "kamaji-etcd.clastix.io/etcd": {{ include "etcd.fullname" . }}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h # 90 days
  renewBefore: 168h # 15 days
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  subject:
    organizations:
      - kamaji-etcd
  commonName: {{ include "etcd.fullname" . }}
  dnsNames:
  {{- $outer := $ -}}
  {{- range $count := until (int $.Values.replicas) }}
    - {{ printf "%s-%d" ( include "etcd.stsName" $outer ) $count }}
    - {{ printf "%s-%d.%s" ( include "etcd.stsName" $outer ) $count (include "etcd.serviceName" $outer) }}
    - {{ printf "%s-%d.%s.%s.svc" ( include "etcd.stsName" $outer ) $count (include "etcd.serviceName" $outer) $.Release.Namespace }}
    - {{ printf "%s-%d.%s.%s.svc.%s" ( include "etcd.stsName" $outer ) $count (include "etcd.serviceName" $outer) $.Release.Namespace $.Values.clusterDomain }}
  {{- end }}
  {{- range .Values.certManager.peerCert.additionalDnsNames }}
    - {{ . | quote }}
  {{- end }}
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ include "etcd.certManager.ca" . }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
{{- end }}
