{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.ca.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.certManager.ca" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.certManager.serverCert" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.certManager.peerCert" .  }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.certManager.clientCert" .  }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
{{- if .Values.certManager.ca.create }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.certManager.ca" . }}
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  duration: {{ .Values.certManager.ca.validity }}
  usages:
    - crl sign
    - cert sign
  commonName: {{ include "etcd.certManager.ca" . }}
  secretName: {{ include "etcd.certManager.ca" . }}
  secretTemplate:
    labels:
      "kamaji-etcd.clastix.io/etcd": {{ include "etcd.fullname" . }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
  {{- toYaml .Values.certManager.issuerRef | nindent 4 }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "etcd.certManager.ca" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "etcd.certManager.ca" . }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.certManager.serverCert" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "etcd.certManager.serverCert" .  }}
  secretTemplate:
    labels:
      "kamaji-etcd.clastix.io/etcd": {{ include "etcd.fullname" . }}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h # 90 days
  renewBefore: 168h # 15 days
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  subject:
    organizations:
      - kamaji-etcd
  commonName: {{ include "etcd.fullname" . }}
  dnsNames:
  {{- $outer := $ -}}
    {{- range $count := until (int $.Values.replicas) }}
    - {{ printf "%s-%d.%s.%s.svc.%s" ( include "etcd.fullname" $outer ) $count (include "etcd.serviceName" $outer) $.Release.Namespace $.Values.clusterDomain }}
    {{- end }}
    - {{ printf "%s.%s.svc.%s" (include "client.serviceName" .) $.Release.Namespace $.Values.clusterDomain }}
    - "etcd-server.{{ .Release.Namespace }}.svc.{{ $.Values.clusterDomain }}"
    - "etcd-server.{{ .Release.Namespace }}.svc"
    - "etcd-server"
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ include "etcd.certManager.ca" . }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.certManager.peerCert" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "etcd.certManager.peerCert" .  }}
  secretTemplate:
    labels:
      "kamaji-etcd.clastix.io/etcd": {{ include "etcd.fullname" . }}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h # 90 days
  renewBefore: 168h # 15 days
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  subject:
    organizations:
      - kamaji-etcd
  commonName: {{ include "etcd.fullname" . }}
  dnsNames:
  {{- $outer := $ -}}
  {{- range $count := until (int $.Values.replicas) }}
    - {{ printf "%s-%d" ( include "etcd.stsName" $outer ) $count }}
    - {{ printf "%s-%d.%s" ( include "etcd.stsName" $outer ) $count (include "etcd.serviceName" $outer) }}
    - {{ printf "%s-%d.%s.%s.svc" ( include "etcd.stsName" $outer ) $count (include "etcd.serviceName" $outer) $.Release.Namespace }}
    - {{ printf "%s-%d.%s.%s.svc.%s" ( include "etcd.stsName" $outer ) $count (include "etcd.serviceName" $outer) $.Release.Namespace $.Values.clusterDomain }}
  {{- end }}
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ include "etcd.certManager.ca" . }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.certManager.clientCert" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "etcd.certManager.clientCert" .  }}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h # 90 days
  renewBefore: 168h # 15 days
  isCA: false
  usages:
    - signing
    - key encipherment
    - client auth
  subject:
    organizations:
      - system:masters
  commonName: root
  issuerRef:
    name: {{ include "etcd.certManager.ca" . }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
