{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.clientCert.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.certManager.clientCert" .  }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "etcd.certManager.clientCert" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "etcd.certManager.clientCert" .  }}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h # 90 days
  renewBefore: 168h # 15 days
  isCA: false
  usages:
    - signing
    - key encipherment
    - client auth
  subject:
    organizations:
      - system:masters
  commonName: root
  issuerRef:
    name: {{ include "etcd.certManager.ca" . }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
{{- end }}
