apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
    prometheus.io/metrics: "true"
  name: {{ include "client.serviceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.clientPort }}
      name: client
    - port: {{ .Values.metricsPort }}
      name: metrics
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
