{{- if .Values.datastore.enabled }}
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: {{ .Values.datastore.name | default (include "etcd.fullname" .) }}
  {{- if .Values.datastore.annotations }}
  annotations:
      {{- toYaml .Values.datastore.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  driver: etcd
  endpoints:
  {{- include "etcd.endpointsYAML" . | nindent 4 }}
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: ca.crt
          name: {{ include "etcd.caSecretName" . }}
          namespace: {{ .Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: ca.key
          name: {{ include "etcd.caSecretName" . }}
          namespace: {{ .Release.Namespace }}
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: {{ include "etcd.clientSecretName" . }}
          namespace: {{ .Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: {{ include "etcd.clientSecretName" . }}
          namespace: {{ .Release.Namespace }}
{{ end }}